### ISSUE TITLE
Source Links 

### ISSUE THREAD

**Issue by TxBillbr** [RepRapster/EBB42-Stealthburner-CW1-Mount#1]
A great enhancement for the project would be links to sources/specs for the flexible strain relief. Thanks for sharing the design.

**Comment by RepRapster** [comment]
Unfortunately the links to the flexible strain relief part purchased from ebay is no longer available and has been relisted so i have included the specs of that part...

**Comment by TxBillbr** [comment]
Thanks for that detail. Searching for "pigtail strain relief" provides a number of sources (and sizes).

**Comment by RepRapster** [comment]
> Thanks for that detail. Searching for "pigtail strain relief" provides a number of sources (and sizes).

this is the re listed part i used ie 5mm version though not sure how long this will be active and also its uk...

https://www.ebay.co.uk/itm/304520603132?mkcid=16&mkevt=1&mkrid=711-127632-2357-0&ssspo=TgpHijk_QW6&sssrc=2349624&ssuid=ZYzUGPZgTGS&var=603539852110&widget_ver=artemis&media=COPY
